project_id = "bhterhkejalvdfxukcwy"
[functions.create-reseller]
enabled = true
verify_jwt = true
import_map = "./functions/create-reseller/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-reseller/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-reseller/*.html" ]

[functions.createReseller]
enabled = true
verify_jwt = true
import_map = "./functions/createReseller/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/createReseller/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/createReseller/*.html" ]
